version: '2'

services:
  dde-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  dde-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
